---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devel
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-devel
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: demo-devel
    spec:
      containers:
      - image: registry.kube-system.svc.cluster.local:5000/test-tekton/tekton-demo:master
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8080
        name: demo
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-devel
spec:
  ports:
  - name: http
    port: 8080
  selector:
    name: demo-devel
